# Generated by Django 6.0.4 on 2026-04-18 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_category_remove_thread_participants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.AddField(
            model_name='message',
            name='copy_recipients',
            field=models.ManyToManyField(blank=True, related_name='copied_messages', to=settings.AUTH_USER_MODEL, verbose_name='Копии'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатели'),
        ),
    ]
