# Generated by Django 6.0.4 on 2026-04-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_remove_message_recipient_message_copy_recipients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='route',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Системный путь'),
        ),
    ]
